set:
  fields:
    entity_id:
      example: var.x
    value:
      example: 13
    value_template:
      example: "{{ input_boolean.foo }}"
    attributes:
      example: |
        attr1: 42
        attr2: "{{ now() }}"
    tracked_entity_id:
      example: input_boolean.bar
    tracked_event_type:
      example: sunset
    query:
      example: "SELECT COUNT(*) AS todays_diaper_count FROM events WHERE event_type = 'diaper_event' AND time_fired BETWEEN DATETIME('now', 'start of day') and DATETIME('now');"
    column:
      example: 'todays_diaper_count'
    restore:
      example: false
    force_update:
      example: true
    unit_of_measurement:
      example: 'ounces'
    icon:
      example: 'mdi:baby-bottle-outline'
    icon_template:
    entity_picture:
      example:  'local/pic.png'
    entity_picture_template:
update:
  fields:
    entity_id:
      example: var.x
